from django.conf.urls.defaults import *

urlpatterns = patterns('point.views',
    url(r'^home$', 'home', { 'force' : 1 }),
    url(r'^$', 'home', name="home"),
    url(r'^$', 'home', name="dashboard"),
    url(r'^create$', 'action.newgroup', name="create"),
    url(r'^like/(\w+)$', 'action.like', name="like"),
    url(r'^comment/(\w+)$', 'action.comment', name="comment"),
    url(r'^editname/(\w+)$', 'action.editname', name="editname"),
    url(r'^read/(\w+)$', 'action.read', name="read"),
    url(r'^more/(\w+)/(\d+)$', 'action.read', name="more"),
    url(r'^post/(\w+)$', 'action.post', name="post"),
    url(r'^invite/(\w+)$', 'action.invite', name="invite"),
    url(r'^shareinvite/(\w+)$', 'action.shareinvite', name="shareinvite"),
    url(r'^gset/(\w+)$', 'action.groupsettings', name="groupsettings"),
    url(r'^accept/(?P<guid>[^/]+)$', 'accept', name="accept"),
    url(r'^waiter$', 'waiter', name="waiter"),
    url(r'^chat/avail$',  'chat.avail', name="chat_avail"),
    url(r'^chat/depart$', 'chat.depart', name="chat_depart"),
    url(r'^email$', 'processemail', name="email"),
    url(r'^r/(?P<gid>[^/]+)/(?P<pid>[^/]+)$', 'readpost', name="readpost"),
    url(r'^a/(?P<id>[^/]+)$', 'accepturl', name="accepturl"),
)
